version: "3.8"

services:
  lint:
    build:
      context: .
      dockerfile: DockerfileForDockerCompose
    image: ${TEXT_LINT_IMAGE_NAME}:${TEXT_LINT_IMAGE_TAG}
    volumes:
      - .:/workspaces/iosdc-pamphlet-template
      - /workspaces/iosdc-pamphlet-template/node_modules
    working_dir: /workspaces/iosdc-pamphlet-template
    command: yarn lint
